import {validBackup} from "./backupData.mjs";
import {useState} from 'react';
export default function Backup({storageId,entries}){
 const [pending,setPending]=useState(null),[error,setError]=useState('');
 const keys=[`talaan-budget-v1-${storageId}`,`talaan-goals-${storageId}`,`talaan-profile-${storageId}`];
 function exportData(){try{const data={version:2,entries,goals:JSON.parse(localStorage.getItem(keys[1])||'[]'),profile:JSON.parse(localStorage.getItem(keys[2])||'{"name":"","startPage":"overview"}')};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='talaan-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError('Could not create a backup. Please try again.');}}
 async function read(file){setError('');setPending(null);if(!file)return;try{if(file.size>5000000)throw Error();const data=JSON.parse(await file.text());if(!validBackup(data))throw Error();setPending(data);}catch{setError('Choose a valid Talaan full backup (version 2), smaller than 5 MB. Nothing was changed.');}}
 function restore(){const old=keys.map(k=>localStorage.getItem(k));try{[pending.entries,pending.goals,pending.profile].forEach((v,i)=>localStorage.setItem(keys[i],JSON.stringify(v)));location.reload();}catch{keys.forEach((k,i)=>{try{old[i]===null?localStorage.removeItem(k):localStorage.setItem(k,old[i]);}catch{}});setError('Restore failed. Your previous data was retained where possible.');}}
 return <section className="settings-block"><h2>Backup & restore</h2><p>A full backup includes events, goals, contributions, and preferences for this workspace.</p><button className="ledger-add" onClick={exportData}>Download full backup</button><label className="restore-label">Restore a backup<input type="file" accept="application/json,.json" onChange={e=>read(e.target.files[0])}/></label>{error&&<p role="alert">{error}</p>}{pending&&<div className="info-panel"><h3>Review before restoring</h3><p>{pending.entries.length} events · {pending.goals.length} goals · profile and preferences</p><p>This replaces this workspace’s data. Download a backup first if you want to keep the current plan.</p><button className="ledger-add" onClick={restore}>Replace with this backup</button><button className="text-action" onClick={()=>setPending(null)}>Cancel restore</button></div>}</section>;
}
