import { useState } from 'react';
import { cashForecast, totalLedger } from '../functions/src/domain/analysis.js';
import './PlanningStudio.css';
import './PlanningTools.css';
import './WorkspaceAnalysis.css';
const cash = cents => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
const emptyId = () => crypto.randomUUID();
function Money({ label, value, onChange, signed = false }) {
  return <label className="planning-field">{label} (USD)<input type="number" min={signed?-1000000:0} max="1000000" step="0.01" value={value/100} onChange={e=>onChange(Math.round(Number(e.target.value)*100))}/></label>;
}
function Editor({ workspace, collection, id, initial, revision = 0, children, onSaved }) {
  const [draft,setDraft]=useState(initial);
  const [base,setBase]=useState(revision);
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState('');
  const [failed,setFailed]=useState(false);
  return <form className="planning-panel settings-form" aria-busy={busy} onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const result=await workspace.command(`${collection}.save`,id,draft,base);setBase(result.revision);setMessage('Saved.');setFailed(false);onSaved?.();}catch(error){setFailed(true);setMessage(error.message);}finally{setBusy(false);}}}>
    {children(draft,(key,value)=>{setDraft(old=>({...old,[key]:value}));setMessage('Unsaved changes');})}
    <div className="drawer-secondary"><button className="ledger-save" disabled={busy||!workspace.capabilities.write}>{busy?'Saving…':'Save'}</button><button type="button" className="text-action" disabled={busy} onClick={()=>{setDraft(initial);setBase(revision);setMessage('Latest record loaded.');setFailed(false);}}>Reload saved record</button></div>
    {message&&<p role={failed?'alert':'status'}>{message}</p>}
  </form>;
}
function Categories({ workspace }) {
  const [name,setName]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const [id,setId]=useState(emptyId);
  return <details className="planning-assumptions"><summary>Manage categories</summary><form className="settings-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await workspace.command('categories.save',id,{name,archived:false});setName('');setId(emptyId());setError('');}catch(error){setError(error.message);}finally{setBusy(false);}}}><label>New category<input required maxLength="60" value={name} onChange={e=>setName(e.target.value)}/></label><button className="ledger-add" disabled={busy||!workspace.capabilities.write}>Add category</button>{error&&<p role="alert">{error}</p>}</form>{workspace.categories.map(category=><Editor key={category.id} workspace={workspace} collection="categories" id={category.id} initial={{name:category.name,archived:category.archived||false}} revision={category.revision}>{(draft,set)=><><label>Category name<input required maxLength="60" value={draft.name} onChange={e=>set('name',e.target.value)}/></label><label><input type="checkbox" checked={draft.archived} onChange={e=>set('archived',e.target.checked)}/> Archived</label></>}</Editor>)}</details>;
}
function Budget({ workspace, period }) {
  const budget=workspace.budgets.find(row=>row.id===period);
  const categories=workspace.categories.filter(row=>!row.archived);
  const records=workspace.ledgerRecords.filter(row=>row.localDate.startsWith(period));
  const totals=totalLedger(records);
  return <section className="plan-tools"><p className="plan-context"><strong>{period} · Your category budget</strong><span>Limits persist. They do not change your events or saved balances.</span></p><div className="plan-workbench"><Editor key={period} workspace={workspace} collection="budgets" id={period} initial={{period,limits:budget?.limits||{}}} revision={budget?.revision||0}>{(draft,set)=><><h2>A little room for each category.</h2>{!categories.length&&<p>Add a category below to begin.</p>}{categories.map(category=>{const planned=records.filter(row=>!row.deleted&&row.type==='expense'&&row.categoryId===category.id).reduce((sum,row)=>sum+row.amountCents,0);return <div key={category.id}><Money label={`${category.name} limit`} value={draft.limits[category.id]||0} onChange={value=>set('limits',{...draft.limits,[category.id]:value})}/><p>{cash(planned)} planned · {cash((draft.limits[category.id]||0)-planned)} room</p></div>;})}<p>Unallocated after limits and planned savings: <strong>{cash(totals.income-totals.saving-Object.values(draft.limits).reduce((sum,value)=>sum+value,0))}</strong></p></>}</Editor><aside className="plan-summary"><h2>Your monthly plan.</h2><p>Income {cash(totals.income)}</p><p>Consumption {cash(totals.expense)}</p><p>Savings {cash(totals.saving)}</p><p>Remainder {cash(totals.remainder)}</p></aside></div><Categories workspace={workspace}/></section>;
}
function Scenarios({ workspace, period }) {
  const [selected,setSelected]=useState('new');const [newId,setNewId]=useState(emptyId);
  const row=workspace.scenarios.find(item=>item.id===selected);
  const totals=totalLedger(workspace.ledgerRecords.filter(event=>event.localDate.startsWith(period)));
  const initial=row?{name:row.name,period:row.period,incomeCents:row.incomeCents,expenseCents:row.expenseCents,savingCents:row.savingCents,baselineRevision:row.baselineRevision}:{name:'New scenario',period,incomeCents:0,expenseCents:0,savingCents:0,baselineRevision:workspace.baselineRevision};
  return <section className="plan-tools"><label className="planning-field">Saved scenario<select value={selected} onChange={e=>{setSelected(e.target.value);setNewId(emptyId());}}><option value="new">Create a scenario</option>{workspace.scenarios.map(item=><option key={item.id} value={item.id}>{item.name} · {item.period}</option>)}</select></label><Editor key={`${selected}:${period}`} workspace={workspace} collection="scenarios" id={row?.id||newId} initial={initial} revision={row?.revision||0} onSaved={()=>setSelected(row?.id||newId)}>{(draft,set)=><><h2>Explore a change.</h2><label>Name<input required maxLength="100" value={draft.name} onChange={e=>set('name',e.target.value)}/></label>{[['incomeCents','Income change'],['expenseCents','Spending change'],['savingCents','Savings change']].map(([key,label])=><Money key={key} label={label} value={draft[key]} signed onChange={value=>set(key,value)}/>)}{draft.baselineRevision!==workspace.baselineRevision&&<p role="status">The workspace has changed since this scenario’s baseline. Review the current totals, then rebase before saving.</p>}<button type="button" className="text-action" onClick={()=>{set('baselineRevision',workspace.baselineRevision);set('period',period);}}>Rebase on {period}</button><p>Current base remainder: {cash(totals.remainder)}</p><p>What-if remainder: <strong>{cash(totals.remainder+draft.incomeCents-draft.expenseCents-draft.savingCents)}</strong></p><p className="planning-caption">A saved scenario never posts money events. Negative deltas reduce the corresponding category.</p></>}</Editor></section>;
}
function Subscriptions({ workspace, today }) {
  const [selected,setSelected]=useState('new'); const [newId,setNewId]=useState(emptyId);
  const row=workspace.subscriptions.find(item=>item.id===selected);
  const initial=row?Object.fromEntries(['name','amountCents','categoryId','frequency','startDate','endDate','status','timezone'].map(key=>[key,row[key]||''])):{name:'',amountCents:0,categoryId:workspace.categories.find(item=>!item.archived)?.id||'',frequency:'monthly',startDate:today,endDate:'',status:'active',timezone:workspace.settings.reminders.timezone};
  return <section className="workspace-flows"><label className="planning-field">Renewal<select value={selected} onChange={e=>{setSelected(e.target.value);setNewId(emptyId());}}><option value="new">Add a subscription</option>{workspace.subscriptions.map(item=><option key={item.id} value={item.id}>{item.name} · {item.status}</option>)}</select></label><Editor key={selected} workspace={workspace} collection="subscriptions" id={row?.id||newId} initial={initial} revision={row?.revision||0} onSaved={()=>setSelected(row?.id||newId)}>{(draft,set)=><><h2>Your renewal details.</h2><label>Name<input required maxLength="100" value={draft.name} onChange={e=>set('name',e.target.value)}/></label><Money label="Price per renewal" value={draft.amountCents} onChange={value=>set('amountCents',value)}/><label>Category<select required value={draft.categoryId} onChange={e=>set('categoryId',e.target.value)}><option value="">Choose a category</option>{workspace.categories.filter(item=>!item.archived).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Billing cycle<select value={draft.frequency} onChange={e=>set('frequency',e.target.value)}><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label>First renewal<input required type="date" value={draft.startDate} onChange={e=>set('startDate',e.target.value)}/></label><label>Status<select value={draft.status} onChange={e=>set('status',e.target.value)}><option value="active">Active in my plan</option><option value="cancelled">Cancelled in my plan</option></select></label><label>{draft.status==='cancelled'?'Cancellation effective date':'Last renewal date (optional)'}<input required={draft.status==='cancelled'} type="date" min={draft.status==='active'?draft.startDate:undefined} value={draft.endDate} onChange={e=>set('endDate',e.target.value)}/></label><p className="planning-caption">This changes your plan only. Contact the provider to cancel the actual service. Existing events retain their original price; changed prices apply to newly generated events.</p><p>Annual equivalent: {cash(draft.amountCents*(draft.frequency==='monthly'?12:1))}</p></>}</Editor></section>;
}
function Analysis({ workspace, period, today, review }) {
  const [days,setDays]=useState(30);const [selected,setSelected]=useState(0);
  const checkpoints=workspace.cashCheckpoints.filter(row=>row.effectiveDate<=today).sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate));
  const checkpoint=checkpoints[0];
  if (review) {
    const rows=workspace.ledgerRecords.filter(row=>row.localDate.startsWith(period));const planned=totalLedger(rows),actual=totalLedger(rows,true);
    return <section className="analysis-workspace"><h2>{period} · Planned and actual</h2><p>Actual means marked completed. Future and unconfirmed entries remain in the plan.</p><table className="flow-table"><thead><tr><th>Measure</th><th>Full plan</th><th>Completed</th></tr></thead><tbody>{['income','expense','saving','remainder'].map(key=><tr key={key}><th>{key}</th><td>{cash(planned[key])}</td><td>{cash(actual[key])}</td></tr>)}</tbody></table><h3>Category details</h3>{workspace.categories.map(category=><details key={category.id}><summary>{category.name}</summary><table className="flow-table"><tbody>{rows.filter(row=>!row.deleted&&row.categoryId===category.id).map(row=><tr key={row.id}><td>{row.localDate}</td><td>{row.name}</td><td>{row.status}</td><td>{cash(row.amountCents)}</td></tr>)}</tbody></table></details>)}</section>;
  }
  let forecast, error;
  try { forecast=cashForecast(workspace.allLedgerRecords,workspace.recurringRules,checkpoint,today,days,workspace.subscriptions); } catch(reason){error=reason.message;}
  const rows=forecast?.timeline||[]; const current=rows[Math.min(selected,rows.length-1)];
  const min=Math.min(0,...rows.map(row=>row.balance)),max=Math.max(1,...rows.map(row=>row.balance));
  const y=value=>220-(value-min)/(max-min||1)*200;
  return <section className="analysis-workspace"><h2>Operating cash from {today}.</h2><div className="planning-segments">{[30,60,90].map(value=><button key={value} aria-pressed={days===value} onClick={()=>{setDays(value);setSelected(0);}}>{value} days</button>)}</div>{error?<p role="status">{error}</p>:<><div className="analysis-metrics"><div><span>Closing projection</span><strong>{cash(rows.at(-1).balance)}</strong></div><div><span>Lowest daily balance</span><strong>{cash(Math.min(...rows.map(row=>row.balance)))}</strong></div></div>{forecast.uncertain>0&&<p role="status">{forecast.uncertain} earlier planned events need confirmation. This projection assumes they occur.</p>}<svg className="analysis-chart" viewBox="0 0 800 240" role="img" aria-label="Projected daily operating cash; full values available in the table below"><line x1="0" x2="800" y1={y(0)} y2={y(0)} stroke="#625e55" strokeDasharray="5 5"/><polyline points={rows.map((row,i)=>`${i/(days-1)*800},${y(row.balance)}`).join(' ')} fill="none" stroke="#a74732" strokeWidth="3"/></svg><label className="planning-range">Inspect date<input type="range" min="0" max={days-1} value={selected} onChange={e=>setSelected(Number(e.target.value))}/></label><p aria-live="polite">{current.date} · {cash(current.balance)}</p><details><summary>Daily balances and events</summary><table className="flow-table"><thead><tr><th>Date</th><th>Balance</th><th>Events</th></tr></thead><tbody>{rows.map(row=><tr key={row.date}><td>{row.date}</td><td>{cash(row.balance)}</td><td>{row.events.map(event=>event.name).join(', ')||'No events'}</td></tr>)}</tbody></table></details></>}
    <details open={!checkpoint}><summary>Set opening operating cash</summary><p>Cash before events on the chosen date. Exclude goal assets. Saved checkpoints do not post income.</p><Editor key={checkpoint?.id||'opening'} workspace={workspace} collection="cashCheckpoints" id={checkpoint?.id||'opening'} initial={{openingCents:checkpoint?.openingCents||0,effectiveDate:checkpoint?.effectiveDate||today}} revision={checkpoint?.revision||0}>{(draft,set)=><><Money label="Opening cash" signed value={draft.openingCents} onChange={value=>set('openingCents',value)}/><label>Effective date<input required type="date" max={today} value={draft.effectiveDate} onChange={e=>set('effectiveDate',e.target.value)}/></label></>}</Editor></details></section>;
}
export default function ConnectedPlanning({ page, workspace, period, today }) {
  return <div className="planning-studio">{page==='budgets'?<Budget workspace={workspace} period={period}/>:page==='scenarios'?<Scenarios workspace={workspace} period={period}/>:page==='subscriptions'?<Subscriptions workspace={workspace} today={today}/>:<Analysis workspace={workspace} period={period} today={today} review={page==='review'}/>}</div>;
}
