import { cash } from './planningData';
import { planningTotals } from './planningToolsState';
import './PlanningTools.css';

function PlanContext() {
  return <p className="plan-context"><strong>September 2026 · Sample plan</strong><span>Adjustments stay while you browse this workspace. Reload restores the sample.</span></p>;
}
function SummaryRow({ label, value }) {
  return <div className="plan-summary-row"><span>{label}</span><strong>{cash(value)}</strong></div>;
}
export function CategoryBudgets({ state, dispatch, onNavigate, model }) {
  const samplePlan = model.plan;
  const totals = planningTotals(state, samplePlan);
  const categories = model.categories;
  return <section className="plan-tools" aria-label="Category budget planner"><PlanContext/><div className="plan-workbench"><section className="planning-panel plan-editor"><div className="planning-section-head"><div><span className="planning-kicker">01 / SET YOUR LIMITS</span><h2>A little room for each category.</h2></div><button className="text-action" onClick={() => dispatch({ type: 'resetLimits' })}>Reset trial limits</button></div><p className="planning-caption">Compare full-month planned spending with your trial limits. These are ceilings, not extra expenses.</p><div className="budget-table-wrap" role="region" aria-label="Scrollable category budget table" tabIndex={0}><table className="budget-editor-table"><caption className="sr-only">Category spending and editable trial limits in USD</caption><thead><tr><th scope="col">Category</th><th scope="col">Planned</th><th scope="col">Trial limit (USD)</th><th scope="col">Room</th></tr></thead><tbody>{categories.map((category, index) => { const room = state.limits[index] - category.spent; return <tr key={category.name}><th scope="row">{category.name}<progress aria-label={`${category.name} planned budget used`} max={Math.max(1, state.limits[index])} value={Math.min(category.spent, state.limits[index])}/></th><td>{cash(category.spent)}</td><td><input aria-label={`${category.name} trial limit (USD)`} type="number" min="0" max="100000" step="1" value={state.limits[index]} onChange={event => dispatch({ type: 'limit', index, value: event.target.value })}/></td><td className={room < 0 ? 'plan-over' : ''}>{cash(Math.abs(room))}<small>{room < 0 ? 'over limit' : 'available'}</small></td></tr>; })}</tbody></table></div></section><aside className="plan-summary" aria-label="Budget summary"><span className="planning-kicker">02 / CHECK THE WHOLE PLAN</span><h2>Make the limits fit.</h2><div aria-live="polite" aria-atomic="true"><p className="plan-total-label">{totals.unallocated < 0 ? 'Limits exceed available income by' : 'Unallocated after limits & savings'}</p><strong className="plan-total">{cash(Math.abs(totals.unallocated))}</strong><SummaryRow label="Sample income" value={samplePlan.income}/><SummaryRow label="Trial category limits" value={totals.limits}/><SummaryRow label="Planned savings" value={samplePlan.savings}/></div><p className="planning-caption">{totals.unallocated < 0 ? 'Lower your limits to leave room for your planned savings.' : 'This room is unassigned in your trial budget.'}</p><div className="plan-summary-note"><SummaryRow label="Planned spending" value={samplePlan.spending}/><p>{cash(Math.abs(totals.headroom))} {totals.headroom < 0 ? 'above your total limits.' : 'below your total limits.'} Check each category too.</p></div><button className="text-action" onClick={() => onNavigate('scenarios')}>Explore a what-if scenario ↗</button><p className="planning-caption">Scenarios use planned spending. Changing a limit does not change spending or your base plan.</p></aside></div></section>;
}
const presets = [['A pay rise', { income: 300, expense: 0, saving: 100 }], ['A new apartment', { income: 0, expense: 350, saving: 0 }], ['Save a little faster', { income: 0, expense: 0, saving: 200 }]];
export function WhatIfScenarios({ state, dispatch, onNavigate, model }) {
  const samplePlan = model.plan;
  const totals = planningTotals(state, samplePlan);
  const controls = [['income', 'Monthly income change', -1500, 1500], ['expense', 'Extra monthly expense', 0, 1500], ['saving', 'Extra monthly savings', 0, 1000]];
  const delta = totals.result - totals.base;
  return <section className="plan-tools" aria-label="What-if scenario planner"><PlanContext/><div className="plan-workbench"><section className="planning-panel plan-editor"><span className="planning-kicker">01 / TRY A CHANGE</span><h2>What could next month look like?</h2><p className="planning-caption">Start with an idea or adjust the amounts. Each preset replaces the current scenario.</p><div className="planning-presets" role="group" aria-label="Sample scenarios">{presets.map(([name, value]) => <button key={name} aria-pressed={Object.keys(value).every(key => value[key] === state.scenario[key])} onClick={() => dispatch({ type: 'scenario', value })}>{name}</button>)}</div>{controls.map(([key, label, min, max]) => <div className="scenario-control" key={key}><label htmlFor={`scenario-${key}`}>{label}<span>USD per month</span></label><input id={`scenario-${key}`} type="number" min={min} max={max} step="1" value={state.scenario[key]} onChange={event => dispatch({ type: 'scenario', value: { ...state.scenario, [key]: event.target.value } })}/><input type="range" aria-label={`${label} slider`} min={min} max={max} step="50" value={state.scenario[key]} onChange={event => dispatch({ type: 'scenario', value: { ...state.scenario, [key]: event.target.value } })}/></div>)}<button className="text-action" onClick={() => dispatch({ type: 'resetScenario' })}>Reset scenario</button><p className="planning-caption">Reset clears only scenario changes. Your trial category limits stay intact.</p></section><aside className="plan-summary scenario-summary" aria-label="Scenario comparison"><span className="planning-kicker">02 / SEE THE DIFFERENCE</span><h2>{totals.result < 0 ? 'This idea needs more room.' : 'Here’s what stays available.'}</h2><div aria-live="polite" aria-atomic="true"><p className="plan-total-label">What-if monthly remainder</p><strong className="plan-total">{cash(totals.result)}</strong><p>{cash(Math.abs(delta))} {delta >= 0 ? 'more' : 'less'} than the base plan.</p><table className="scenario-totals"><caption className="sr-only">Base plan compared with scenario, in USD</caption><thead><tr><th scope="col">Monthly plan</th><th scope="col">Base</th><th scope="col">What-if</th></tr></thead><tbody>{[['Income', samplePlan.income, totals.income], ['Spending', samplePlan.spending, totals.spending], ['Savings', samplePlan.savings, totals.savings], ['Remainder', totals.base, totals.result]].map(([label, base, result]) => <tr key={label}><th scope="row">{label}</th><td>{cash(base)}</td><td>{cash(result)}</td></tr>)}</tbody></table></div><p className="plan-isolation">Scenario only. Your base plan stays unchanged. Nothing is applied or saved to an account.</p><button className="text-action" onClick={() => onNavigate('budgets')}>Review category limits ↗</button></aside></div></section>;
}
