import { money, EventTable } from './WorkspaceSchedule';

export default function WorkspaceOverview({ monthly, goals, income, out, available, mood, face, today, onEdit, onNavigate }) {
  const upcoming = monthly.filter(event => event.date >= today && event.status !== 'completed').sort((a,b) => a.date.localeCompare(b.date));
  const outstanding = monthly.filter(event => event.date < today && event.status !== 'completed');
  const expenses = upcoming.filter(event => event.type === 'expense');
  const due = expenses.reduce((sum,event) => sum + Math.round(event.amount * 100), 0) / 100;
  return <div className="overview-layout">
    <div className="overview-top">
      <section className="overview-balance"><div className="workspace-label"><span>MONTHLY POSITION</span><span>USD</span></div><div className="balance-with-face"><div><p>{available < 0 ? 'Over budget by' : 'Planned remaining'}</p><strong className="overview-amount">{money(Math.abs(available))}</strong></div>{face}</div><p className="overview-balance-note">{mood}. Includes future income; not your bank balance.</p><div className="overview-money-split"><div><span>Planned income</span><strong>{money(income)}</strong></div><div><span>Planned outflow</span><strong>{money(out)}</strong></div></div><details className="mood-help"><summary>How is this calculated?</summary><p>Monthly income minus all planned expenses, including savings entries. A negative remainder is over budget; less than 10% of income remaining is getting tight. This is a plan indicator.</p></details></section>
      <section className="overview-attention"><span className="workspace-eyebrow">YOUR NEXT STEPS</span><h2>A little attention goes a long way.</h2><div className="attention-line"><strong>{outstanding.length}</strong><div><span>Past events to confirm</span><small>Check whether these happened.</small></div></div><div className="attention-line"><strong>{money(due)}</strong><div><span>Upcoming money out</span><small>{expenses.length} pending {expenses.length === 1 ? 'expense' : 'expenses'} this month.</small></div></div><button className="text-action" onClick={() => onNavigate('schedule')}>Review your schedule ↗</button></section>
    </div>
    <div className="overview-bottom"><section className="overview-upcoming"><div className="section-heading"><div><span className="workspace-eyebrow">COMING UP</span><h2>Your next money moments.</h2></div><button className="text-action" onClick={() => onNavigate('schedule')}>View all ↗</button></div><EventTable entries={upcoming.slice(0,5)} today={today} onEdit={onEdit} compact empty="Nothing else scheduled this month." /></section><section className="overview-goals"><div className="section-heading"><div><span className="workspace-eyebrow">LOOKING AHEAD</span><h2>Savings progress.</h2></div></div>{goals.length ? goals.slice(0,3).map(goal => <div className="overview-goal" key={goal.id}><strong>{goal.name}</strong><p>{money(goal.saved)} <span>of {money(goal.target)}</span></p><progress aria-label={`${goal.name} savings progress`} value={Math.min(goal.saved,goal.target)} max={goal.target}/><small>{Math.round(goal.saved / goal.target * 100)}% saved · {money(Math.max(0,goal.target-goal.saved))} to go</small></div>) : <p className="ledger-empty">Give your next savings goal a home.</p>}<button className="text-action" onClick={() => onNavigate('goals')}>{goals.length ? 'View goals' : 'Create a goal'} ↗</button></section></div>
  </div>;
}
