export const money = value => new Intl.NumberFormat('en-US', { style:'currency', currency:'USD', maximumFractionDigits:2 }).format(value);
export function eventStatus(entry, today) {
  if (entry.status === 'completed') return entry.type === 'income' ? 'Received' : entry.type === 'saving' ? 'Saved' : 'Paid';
  return entry.date < today ? 'Unconfirmed' : entry.date === today ? 'Due today' : 'Planned';
}
export function EventTable({ entries, today, onEdit, compact = false, empty = 'No matching events. Try another search or filter.' }) {
  if (!entries.length) return <div className="schedule-empty"><h3>A little room here.</h3><p>{empty}</p></div>;
  return <div role="region" tabIndex={0} aria-label={compact ? "Upcoming events table" : "Scheduled events table"} className={`event-table-wrap ${compact ? 'compact' : ''}`}><table className="event-table"><caption className="sr-only">{compact ? 'Upcoming events' : 'Scheduled money events'}</caption><thead><tr><th scope="col">Event</th><th scope="col">Date</th>{!compact && <th scope="col" className="event-category">Category</th>}<th scope="col">Status</th><th scope="col" className="event-money">Amount</th></tr></thead><tbody>{entries.map(entry => <tr key={entry.id}><td><button className="event-name" onClick={event => onEdit(entry,event.currentTarget)} aria-label={`Edit ${entry.name} on ${entry.date}`}>{entry.name}<span aria-hidden="true">↗</span></button><small className="event-mobile-date">{new Date(`${entry.date}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</small></td><td className="event-date-cell"><time dateTime={entry.date}>{new Date(`${entry.date}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time></td>{!compact && <td className="event-category">{entry.type === 'income' ? 'Money in' : entry.category}</td>}<td><span className={`event-status ${entry.status === 'completed' ? 'confirmed' : entry.date < today ? 'unconfirmed' : ''}`}>{eventStatus(entry,today)}</span></td><td className={`event-money ${entry.type === 'income' ? 'money-in' : ''}`}>{entry.type === 'income' ? '+' : '−'}{money(entry.amount)}</td></tr>)}</tbody></table></div>;
}
export default function WorkspaceSchedule({ entries, today, query, onQuery, kind, onKind, status, onStatus, onEdit, totalCount }) {
  const reset = () => { onQuery(''); onKind('all'); onStatus('all'); };
  const filtered = query || kind !== 'all' || status !== 'all';
  return <section className="schedule-workspace" aria-label="Event list"><div className="event-toolbar"><label className="event-search-label">Search events<input type="search" placeholder="Search name or category" value={query} onChange={event => onQuery(event.target.value)}/></label><label>Type<select value={kind} onChange={event => onKind(event.target.value)}><option value="all">All events</option><option value="income">Money in</option><option value="expense">Money out</option><option value="saving">Savings</option></select></label><label>Status<select value={status} onChange={event => onStatus(event.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="unconfirmed">Unconfirmed</option><option value="completed">Completed</option></select></label><button className="text-action" disabled={!filtered} onClick={reset}>Clear filters</button></div><div className="event-list-summary"><span role="status">{entries.length} of {totalCount} events</span><span>Date order · USD</span></div><EventTable entries={entries} today={today} onEdit={onEdit} empty={filtered ? 'No matching events. Clear filters or try another search.' : 'Add a payday, bill, or savings entry to begin.'}/></section>;
}
